"""Bounded Execution Ledger token registry for backend contract use.

This module defines canonical token vocabularies for Execution Ledger planning
and proof semantics. It intentionally does not wire tokens into runtime routes,
workers, stores, or API surfaces in this task.
"""

from __future__ import annotations

# Gate phases
GATE_PHASE_INTENT_SCOPE = "intent_scope"
GATE_PHASE_IMPLEMENTATION_PLAN = "implementation_plan"
GATE_PHASE_COMPLETION_PROOF = "completion_proof"

# Gate decisions
GATE_DECISION_PENDING = "pending"
GATE_DECISION_APPROVED = "approved"
GATE_DECISION_REJECTED = "rejected"
GATE_DECISION_CHANGES_REQUESTED = "changes_requested"
GATE_DECISION_DEFERRED = "deferred"
GATE_DECISION_SUPERSEDED = "superseded"

# Plan states
PLAN_STATE_NOT_STARTED = "not_started"
PLAN_STATE_DRAFT = "draft"
PLAN_STATE_READY_FOR_REVIEW = "ready_for_review"
PLAN_STATE_APPROVED = "approved"
PLAN_STATE_CHANGES_REQUESTED = "changes_requested"
PLAN_STATE_SUPERSEDED = "superseded"
PLAN_STATE_ABANDONED = "abandoned"

# Acceptance validation modes
ACCEPTANCE_VALIDATION_MODE_MANUAL_REVIEW = "manual_review"
ACCEPTANCE_VALIDATION_MODE_UNIT_TEST = "unit_test"
ACCEPTANCE_VALIDATION_MODE_INTEGRATION_TEST = "integration_test"
ACCEPTANCE_VALIDATION_MODE_TYPECHECK = "typecheck"
ACCEPTANCE_VALIDATION_MODE_LINT = "lint"
ACCEPTANCE_VALIDATION_MODE_RUNTIME_PROBE = "runtime_probe"
ACCEPTANCE_VALIDATION_MODE_DOCS_VALIDATION = "docs_validation"
ACCEPTANCE_VALIDATION_MODE_DIFF_INSPECTION = "diff_inspection"

# Acceptance criterion results
ACCEPTANCE_CRITERION_RESULT_NOT_CHECKED = "not_checked"
ACCEPTANCE_CRITERION_RESULT_PASSED = "passed"
ACCEPTANCE_CRITERION_RESULT_FAILED = "failed"
ACCEPTANCE_CRITERION_RESULT_BLOCKED = "blocked"
ACCEPTANCE_CRITERION_RESULT_NOT_APPLICABLE = "not_applicable"

# Proof decisions
PROOF_DECISION_PROOF_PENDING = "proof_pending"
PROOF_DECISION_PROOF_ACCEPTED = "proof_accepted"
PROOF_DECISION_PROOF_REJECTED = "proof_rejected"
PROOF_DECISION_FOLLOW_UP_REQUIRED = "follow_up_required"
PROOF_DECISION_EVIDENCE_INCOMPLETE = "evidence_incomplete"

# Escalation reasons
ESCALATION_REASON_SCOPE_UNCLEAR = "scope_unclear"
ESCALATION_REASON_PLAN_REJECTED = "plan_rejected"
ESCALATION_REASON_VALIDATION_FAILED = "validation_failed"
ESCALATION_REASON_DELIVERY_FAILED = "delivery_failed"
ESCALATION_REASON_LINEAGE_MISSING = "lineage_missing"
ESCALATION_REASON_ATTEMPT_FAILED = "attempt_failed"
ESCALATION_REASON_EVIDENCE_INCOMPLETE = "evidence_incomplete"
ESCALATION_REASON_OUT_OF_SCOPE_CHANGE = "out_of_scope_change"
ESCALATION_REASON_REQUIRES_HUMAN_DECISION = "requires_human_decision"

GATE_PHASES: tuple[str, ...] = (
    GATE_PHASE_INTENT_SCOPE,
    GATE_PHASE_IMPLEMENTATION_PLAN,
    GATE_PHASE_COMPLETION_PROOF,
)

GATE_DECISIONS: tuple[str, ...] = (
    GATE_DECISION_PENDING,
    GATE_DECISION_APPROVED,
    GATE_DECISION_REJECTED,
    GATE_DECISION_CHANGES_REQUESTED,
    GATE_DECISION_DEFERRED,
    GATE_DECISION_SUPERSEDED,
)

PLAN_STATES: tuple[str, ...] = (
    PLAN_STATE_NOT_STARTED,
    PLAN_STATE_DRAFT,
    PLAN_STATE_READY_FOR_REVIEW,
    PLAN_STATE_APPROVED,
    PLAN_STATE_CHANGES_REQUESTED,
    PLAN_STATE_SUPERSEDED,
    PLAN_STATE_ABANDONED,
)

ACCEPTANCE_VALIDATION_MODES: tuple[str, ...] = (
    ACCEPTANCE_VALIDATION_MODE_MANUAL_REVIEW,
    ACCEPTANCE_VALIDATION_MODE_UNIT_TEST,
    ACCEPTANCE_VALIDATION_MODE_INTEGRATION_TEST,
    ACCEPTANCE_VALIDATION_MODE_TYPECHECK,
    ACCEPTANCE_VALIDATION_MODE_LINT,
    ACCEPTANCE_VALIDATION_MODE_RUNTIME_PROBE,
    ACCEPTANCE_VALIDATION_MODE_DOCS_VALIDATION,
    ACCEPTANCE_VALIDATION_MODE_DIFF_INSPECTION,
)

ACCEPTANCE_CRITERION_RESULTS: tuple[str, ...] = (
    ACCEPTANCE_CRITERION_RESULT_NOT_CHECKED,
    ACCEPTANCE_CRITERION_RESULT_PASSED,
    ACCEPTANCE_CRITERION_RESULT_FAILED,
    ACCEPTANCE_CRITERION_RESULT_BLOCKED,
    ACCEPTANCE_CRITERION_RESULT_NOT_APPLICABLE,
)

PROOF_DECISIONS: tuple[str, ...] = (
    PROOF_DECISION_PROOF_PENDING,
    PROOF_DECISION_PROOF_ACCEPTED,
    PROOF_DECISION_PROOF_REJECTED,
    PROOF_DECISION_FOLLOW_UP_REQUIRED,
    PROOF_DECISION_EVIDENCE_INCOMPLETE,
)

ESCALATION_REASONS: tuple[str, ...] = (
    ESCALATION_REASON_SCOPE_UNCLEAR,
    ESCALATION_REASON_PLAN_REJECTED,
    ESCALATION_REASON_VALIDATION_FAILED,
    ESCALATION_REASON_DELIVERY_FAILED,
    ESCALATION_REASON_LINEAGE_MISSING,
    ESCALATION_REASON_ATTEMPT_FAILED,
    ESCALATION_REASON_EVIDENCE_INCOMPLETE,
    ESCALATION_REASON_OUT_OF_SCOPE_CHANGE,
    ESCALATION_REASON_REQUIRES_HUMAN_DECISION,
)

_GATE_PHASE_SET: frozenset[str] = frozenset(GATE_PHASES)
_GATE_DECISION_SET: frozenset[str] = frozenset(GATE_DECISIONS)
_PLAN_STATE_SET: frozenset[str] = frozenset(PLAN_STATES)
_ACCEPTANCE_VALIDATION_MODE_SET: frozenset[str] = frozenset(
    ACCEPTANCE_VALIDATION_MODES
)
_ACCEPTANCE_CRITERION_RESULT_SET: frozenset[str] = frozenset(
    ACCEPTANCE_CRITERION_RESULTS
)
_PROOF_DECISION_SET: frozenset[str] = frozenset(PROOF_DECISIONS)
_ESCALATION_REASON_SET: frozenset[str] = frozenset(ESCALATION_REASONS)


def is_valid_gate_phase(value: str) -> bool:
    return isinstance(value, str) and value in _GATE_PHASE_SET


def is_valid_gate_decision(value: str) -> bool:
    return isinstance(value, str) and value in _GATE_DECISION_SET


def is_valid_plan_state(value: str) -> bool:
    return isinstance(value, str) and value in _PLAN_STATE_SET


def is_valid_acceptance_validation_mode(value: str) -> bool:
    return isinstance(value, str) and value in _ACCEPTANCE_VALIDATION_MODE_SET


def is_valid_acceptance_criterion_result(value: str) -> bool:
    return isinstance(value, str) and value in _ACCEPTANCE_CRITERION_RESULT_SET


def is_valid_proof_decision(value: str) -> bool:
    return isinstance(value, str) and value in _PROOF_DECISION_SET


def is_valid_escalation_reason(value: str) -> bool:
    return isinstance(value, str) and value in _ESCALATION_REASON_SET


__all__ = [
    "GATE_PHASE_INTENT_SCOPE",
    "GATE_PHASE_IMPLEMENTATION_PLAN",
    "GATE_PHASE_COMPLETION_PROOF",
    "GATE_DECISION_PENDING",
    "GATE_DECISION_APPROVED",
    "GATE_DECISION_REJECTED",
    "GATE_DECISION_CHANGES_REQUESTED",
    "GATE_DECISION_DEFERRED",
    "GATE_DECISION_SUPERSEDED",
    "PLAN_STATE_NOT_STARTED",
    "PLAN_STATE_DRAFT",
    "PLAN_STATE_READY_FOR_REVIEW",
    "PLAN_STATE_APPROVED",
    "PLAN_STATE_CHANGES_REQUESTED",
    "PLAN_STATE_SUPERSEDED",
    "PLAN_STATE_ABANDONED",
    "ACCEPTANCE_VALIDATION_MODE_MANUAL_REVIEW",
    "ACCEPTANCE_VALIDATION_MODE_UNIT_TEST",
    "ACCEPTANCE_VALIDATION_MODE_INTEGRATION_TEST",
    "ACCEPTANCE_VALIDATION_MODE_TYPECHECK",
    "ACCEPTANCE_VALIDATION_MODE_LINT",
    "ACCEPTANCE_VALIDATION_MODE_RUNTIME_PROBE",
    "ACCEPTANCE_VALIDATION_MODE_DOCS_VALIDATION",
    "ACCEPTANCE_VALIDATION_MODE_DIFF_INSPECTION",
    "ACCEPTANCE_CRITERION_RESULT_NOT_CHECKED",
    "ACCEPTANCE_CRITERION_RESULT_PASSED",
    "ACCEPTANCE_CRITERION_RESULT_FAILED",
    "ACCEPTANCE_CRITERION_RESULT_BLOCKED",
    "ACCEPTANCE_CRITERION_RESULT_NOT_APPLICABLE",
    "PROOF_DECISION_PROOF_PENDING",
    "PROOF_DECISION_PROOF_ACCEPTED",
    "PROOF_DECISION_PROOF_REJECTED",
    "PROOF_DECISION_FOLLOW_UP_REQUIRED",
    "PROOF_DECISION_EVIDENCE_INCOMPLETE",
    "ESCALATION_REASON_SCOPE_UNCLEAR",
    "ESCALATION_REASON_PLAN_REJECTED",
    "ESCALATION_REASON_VALIDATION_FAILED",
    "ESCALATION_REASON_DELIVERY_FAILED",
    "ESCALATION_REASON_LINEAGE_MISSING",
    "ESCALATION_REASON_ATTEMPT_FAILED",
    "ESCALATION_REASON_EVIDENCE_INCOMPLETE",
    "ESCALATION_REASON_OUT_OF_SCOPE_CHANGE",
    "ESCALATION_REASON_REQUIRES_HUMAN_DECISION",
    "GATE_PHASES",
    "GATE_DECISIONS",
    "PLAN_STATES",
    "ACCEPTANCE_VALIDATION_MODES",
    "ACCEPTANCE_CRITERION_RESULTS",
    "PROOF_DECISIONS",
    "ESCALATION_REASONS",
    "is_valid_gate_phase",
    "is_valid_gate_decision",
    "is_valid_plan_state",
    "is_valid_acceptance_validation_mode",
    "is_valid_acceptance_criterion_result",
    "is_valid_proof_decision",
    "is_valid_escalation_reason",
]
