"""Canonical identity precedence tokens for Codexify.

These names are shared by prompt assembly, runtime resolution, and
inspector/status surfaces.
"""

from __future__ import annotations

from typing import Final

from guardian.cognition.modular_prompt_builder import (
    SEGMENT_ORDER as IDENTITY_PROMPT_ASSEMBLY_ORDER,
)

IDENTITY_RUNTIME_POSTURE_ACTOR_PLUS_ROLE: Final[str] = "actor_plus_role"

IDENTITY_LAYER_CORE_PLATFORM: Final[str] = "core_platform"
IDENTITY_LAYER_IMPRINT: Final[str] = "imprint"
IDENTITY_LAYER_PERSONA: Final[str] = "persona"
IDENTITY_LAYER_REQUEST_OVERRIDE: Final[str] = "request_override"
IDENTITY_LAYER_THREAD_OVERRIDE: Final[str] = "thread_override"
IDENTITY_LAYER_SYSTEM_DOCS: Final[str] = "system_docs"
IDENTITY_LAYER_SCRATCHPAD: Final[str] = "scratchpad"

PERSONA_RESOLUTION_SOURCE_REQUEST_OVERRIDE: Final[str] = "request_override"
PERSONA_RESOLUTION_SOURCE_ACTIVE_SCOPE: Final[str] = "active_scope"
PERSONA_RESOLUTION_SOURCE_PROJECT_DEFAULT: Final[str] = "project_default"
PERSONA_RESOLUTION_SOURCE_SYSTEM_DEFAULT: Final[str] = "system_default"

IMPRINT_RESOLUTION_SOURCE_ACTIVE_SCOPE: Final[str] = "active_scope"
IMPRINT_RESOLUTION_SOURCE_USER_DEFAULT: Final[str] = "user_default"
IMPRINT_RESOLUTION_SOURCE_SYSTEM_DEFAULT: Final[str] = "system_default"

IDENTITY_PERSONA_RESOLUTION_ORDER: Final[tuple[str, ...]] = (
    PERSONA_RESOLUTION_SOURCE_REQUEST_OVERRIDE,
    PERSONA_RESOLUTION_SOURCE_ACTIVE_SCOPE,
    PERSONA_RESOLUTION_SOURCE_PROJECT_DEFAULT,
    PERSONA_RESOLUTION_SOURCE_SYSTEM_DEFAULT,
)

IDENTITY_IMPRINT_RESOLUTION_ORDER: Final[tuple[str, ...]] = (
    IMPRINT_RESOLUTION_SOURCE_ACTIVE_SCOPE,
    IMPRINT_RESOLUTION_SOURCE_USER_DEFAULT,
    IMPRINT_RESOLUTION_SOURCE_SYSTEM_DEFAULT,
)

__all__ = [
    "IDENTITY_IMPRINT_RESOLUTION_ORDER",
    "IDENTITY_LAYER_CORE_PLATFORM",
    "IDENTITY_LAYER_IMPRINT",
    "IDENTITY_LAYER_PERSONA",
    "IDENTITY_LAYER_REQUEST_OVERRIDE",
    "IDENTITY_LAYER_SCRATCHPAD",
    "IDENTITY_LAYER_SYSTEM_DOCS",
    "IDENTITY_LAYER_THREAD_OVERRIDE",
    "IDENTITY_PERSONA_RESOLUTION_ORDER",
    "IDENTITY_PROMPT_ASSEMBLY_ORDER",
    "IDENTITY_RUNTIME_POSTURE_ACTOR_PLUS_ROLE",
    "IMPRINT_RESOLUTION_SOURCE_ACTIVE_SCOPE",
    "IMPRINT_RESOLUTION_SOURCE_SYSTEM_DEFAULT",
    "IMPRINT_RESOLUTION_SOURCE_USER_DEFAULT",
    "PERSONA_RESOLUTION_SOURCE_ACTIVE_SCOPE",
    "PERSONA_RESOLUTION_SOURCE_PROJECT_DEFAULT",
    "PERSONA_RESOLUTION_SOURCE_REQUEST_OVERRIDE",
    "PERSONA_RESOLUTION_SOURCE_SYSTEM_DEFAULT",
]
