"""add collaboration and sharing tables

Revision ID: 13a4a6dc5ba1
Revises: 83c2f0bb0dfa
Create Date: 2026-01-26 19:36:35.737603

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "13a4a6dc5ba1"
down_revision: Union[str, Sequence[str], None] = "83c2f0bb0dfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collaboration_audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_collab_audit_doc",
        "collaboration_audit_log",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        "ix_collab_audit_doc_timestamp",
        "collaboration_audit_log",
        ["document_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_collab_audit_user",
        "collaboration_audit_log",
        ["user_id"],
        unique=False,
    )

    op.create_table(
        "collaboration_permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "can_edit", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "can_comment", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("granted_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_collab_perms_doc_user",
        "collaboration_permissions",
        ["document_id", "user_id"],
        unique=True,
    )
    op.create_index(
        "ix_collab_perms_document",
        "collaboration_permissions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        "ix_collab_perms_user",
        "collaboration_permissions",
        ["user_id"],
        unique=False,
    )

    op.create_table(
        "shared_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type IN ('thread', 'document')",
            name="shared_links_target_type_check",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )

    op.create_table(
        "thread_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column(
            "relation",
            sa.String(length=64),
            server_default="autosave",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relation IN ('autosave', 'attached', 'reference')",
            name="thread_documents_relation_check",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["chat_threads.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: this migration is intentionally limited to ONLY the new collaboration/sharing tables.
    # It must not rewrite unrelated schema.

    # Drop in reverse dependency order
    op.drop_table("thread_documents")
    op.drop_table("shared_links")

    # collaboration_permissions indexes
    op.drop_index(
        "ix_collab_perms_user", table_name="collaboration_permissions"
    )
    op.drop_index(
        "ix_collab_perms_document", table_name="collaboration_permissions"
    )
    op.drop_index(
        "ix_collab_perms_doc_user", table_name="collaboration_permissions"
    )
    op.drop_table("collaboration_permissions")

    # collaboration_audit_log indexes
    op.drop_index("ix_collab_audit_user", table_name="collaboration_audit_log")
    op.drop_index(
        "ix_collab_audit_doc_timestamp", table_name="collaboration_audit_log"
    )
    op.drop_index("ix_collab_audit_doc", table_name="collaboration_audit_log")
    op.drop_table("collaboration_audit_log")
    # ### end Alembic commands ###
