"""add collaboration and sharing tables

Revision ID: 13a4a6dc5ba1
Revises: 83c2f0bb0dfa
Create Date: 2026-01-26 19:36:35.737603

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "13a4a6dc5ba1"
down_revision: Union[str, Sequence[str], None] = "83c2f0bb0dfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return table_name in inspector.get_table_names()


def _has_index(table_name: str, index_name: str) -> bool:
    if not _has_table(table_name):
        return False
    inspector = sa.inspect(op.get_bind())
    return index_name in {
        idx["name"] for idx in inspector.get_indexes(table_name)
    }


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_table("collaboration_audit_log"):
        op.create_table(
            "collaboration_audit_log",
            sa.Column(
                "id", sa.BigInteger(), autoincrement=True, nullable=False
            ),
            sa.Column("document_id", sa.String(length=36), nullable=False),
            sa.Column("user_id", sa.String(length=255), nullable=True),
            sa.Column("action", sa.String(length=64), nullable=False),
            sa.Column(
                "payload",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=True,
            ),
            sa.Column(
                "timestamp",
                sa.TIMESTAMP(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if not _has_index("collaboration_audit_log", "ix_collab_audit_doc"):
        op.create_index(
            "ix_collab_audit_doc",
            "collaboration_audit_log",
            ["document_id"],
            unique=False,
        )
    if not _has_index(
        "collaboration_audit_log", "ix_collab_audit_doc_timestamp"
    ):
        op.create_index(
            "ix_collab_audit_doc_timestamp",
            "collaboration_audit_log",
            ["document_id", "timestamp"],
            unique=False,
        )
    if not _has_index("collaboration_audit_log", "ix_collab_audit_user"):
        op.create_index(
            "ix_collab_audit_user",
            "collaboration_audit_log",
            ["user_id"],
            unique=False,
        )

    if not _has_table("collaboration_permissions"):
        op.create_table(
            "collaboration_permissions",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("document_id", sa.String(length=36), nullable=False),
            sa.Column("user_id", sa.String(length=255), nullable=False),
            sa.Column(
                "can_edit", sa.Boolean(), server_default="false", nullable=False
            ),
            sa.Column(
                "can_comment",
                sa.Boolean(),
                server_default="true",
                nullable=False,
            ),
            sa.Column("granted_by", sa.String(length=255), nullable=False),
            sa.Column(
                "created_at",
                sa.TIMESTAMP(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if not _has_index("collaboration_permissions", "ix_collab_perms_doc_user"):
        op.create_index(
            "ix_collab_perms_doc_user",
            "collaboration_permissions",
            ["document_id", "user_id"],
            unique=True,
        )
    if not _has_index("collaboration_permissions", "ix_collab_perms_document"):
        op.create_index(
            "ix_collab_perms_document",
            "collaboration_permissions",
            ["document_id"],
            unique=False,
        )
    if not _has_index("collaboration_permissions", "ix_collab_perms_user"):
        op.create_index(
            "ix_collab_perms_user",
            "collaboration_permissions",
            ["user_id"],
            unique=False,
        )

    if not _has_table("shared_links"):
        op.create_table(
            "shared_links",
            sa.Column("id", sa.String(length=36), nullable=False),
            sa.Column("target_type", sa.String(length=32), nullable=False),
            sa.Column("target_id", sa.Integer(), nullable=False),
            sa.Column("token", sa.String(length=64), nullable=False),
            sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
            sa.Column(
                "created_at",
                sa.TIMESTAMP(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.CheckConstraint(
                "target_type IN ('thread', 'document')",
                name="shared_links_target_type_check",
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("token"),
        )

    if not _has_table("thread_documents"):
        op.create_table(
            "thread_documents",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("thread_id", sa.Integer(), nullable=False),
            sa.Column("document_id", sa.String(length=36), nullable=False),
            sa.Column(
                "relation",
                sa.String(length=64),
                server_default="autosave",
                nullable=False,
            ),
            sa.Column(
                "created_at",
                sa.TIMESTAMP(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.CheckConstraint(
                "relation IN ('autosave', 'attached', 'reference')",
                name="thread_documents_relation_check",
            ),
            sa.ForeignKeyConstraint(
                ["thread_id"], ["chat_threads.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: this migration is intentionally limited to ONLY the new collaboration/sharing tables.
    # It must not rewrite unrelated schema.

    # Drop in reverse dependency order
    if _has_table("thread_documents"):
        op.drop_table("thread_documents")
    if _has_table("shared_links"):
        op.drop_table("shared_links")

    # collaboration_permissions indexes
    if _has_index("collaboration_permissions", "ix_collab_perms_user"):
        op.drop_index(
            "ix_collab_perms_user", table_name="collaboration_permissions"
        )
    if _has_index("collaboration_permissions", "ix_collab_perms_document"):
        op.drop_index(
            "ix_collab_perms_document", table_name="collaboration_permissions"
        )
    if _has_index("collaboration_permissions", "ix_collab_perms_doc_user"):
        op.drop_index(
            "ix_collab_perms_doc_user",
            table_name="collaboration_permissions",
        )
    if _has_table("collaboration_permissions"):
        op.drop_table("collaboration_permissions")

    # collaboration_audit_log indexes
    if _has_index("collaboration_audit_log", "ix_collab_audit_user"):
        op.drop_index(
            "ix_collab_audit_user", table_name="collaboration_audit_log"
        )
    if _has_index("collaboration_audit_log", "ix_collab_audit_doc_timestamp"):
        op.drop_index(
            "ix_collab_audit_doc_timestamp",
            table_name="collaboration_audit_log",
        )
    if _has_index("collaboration_audit_log", "ix_collab_audit_doc"):
        op.drop_index(
            "ix_collab_audit_doc", table_name="collaboration_audit_log"
        )
    if _has_table("collaboration_audit_log"):
        op.drop_table("collaboration_audit_log")
    # ### end Alembic commands ###
