"""add media and tts tables

Revision ID: 9373693cc12e
Revises: ac973209add4
Create Date: 2025-10-26 22:18:49.510333

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9373693cc12e"
down_revision: Union[str, Sequence[str], None] = "ac973209add4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generated_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "format IN ('txt', 'md', 'docx', 'pdf', 'html', 'json')",
            name="generated_documents_format_check",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["chat_threads.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_generated_documents_created",
        "generated_documents",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_generated_documents_format",
        "generated_documents",
        ["format"],
        unique=False,
    )
    op.create_index(
        "ix_generated_documents_project",
        "generated_documents",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_generated_documents_thread",
        "generated_documents",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "generated_images",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("src_url", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["chat_threads.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_generated_images_created",
        "generated_images",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_generated_images_project",
        "generated_images",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_generated_images_thread",
        "generated_images",
        ["thread_id"],
        unique=False,
    )
    op.create_index(
        "ix_generated_images_user",
        "generated_images",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "tts_outputs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("voice", sa.String(length=128), nullable=True),
        sa.Column("provider", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("src_url", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["chat_threads.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tts_outputs_created",
        "tts_outputs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_tts_outputs_project", "tts_outputs", ["project_id"], unique=False
    )
    op.create_index(
        "ix_tts_outputs_provider", "tts_outputs", ["provider"], unique=False
    )
    op.create_index(
        "ix_tts_outputs_thread", "tts_outputs", ["thread_id"], unique=False
    )
    op.create_table(
        "uploaded_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("filesize", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("src_url", sa.Text(), nullable=False),
        sa.Column("parsed_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["chat_threads.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_uploaded_documents_created",
        "uploaded_documents",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_uploaded_documents_mime",
        "uploaded_documents",
        ["mime_type"],
        unique=False,
    )
    op.create_index(
        "ix_uploaded_documents_project",
        "uploaded_documents",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_uploaded_documents_thread",
        "uploaded_documents",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "uploaded_images",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("src_url", sa.Text(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("filesize", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["chat_threads.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_uploaded_images_created",
        "uploaded_images",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_uploaded_images_mime",
        "uploaded_images",
        ["mime_type"],
        unique=False,
    )
    op.create_index(
        "ix_uploaded_images_project",
        "uploaded_images",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_uploaded_images_thread",
        "uploaded_images",
        ["thread_id"],
        unique=False,
    )
    op.create_index(
        "ix_uploaded_images_user", "uploaded_images", ["user_id"], unique=False
    )
    op.alter_column(
        "events_outbox",
        "tenant_id",
        existing_type=sa.VARCHAR(length=64),
        server_default="default",
        existing_nullable=False,
    )
    # These legacy indexes were previously created by runtime DDL in code, not Alembic.
    # On fresh Alembic-managed databases they may not exist, so drop them conditionally.
    # Conditional drop added to handle fresh Alembic environments (no legacy runtime DDL).
    op.execute("DROP INDEX IF EXISTS idx_events_outbox_created")
    op.execute("DROP INDEX IF EXISTS idx_sync_jobs_connector_created")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_sync_jobs_connector_created"),
        "sync_jobs",
        ["connector_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_events_outbox_created"),
        "events_outbox",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "events_outbox",
        "tenant_id",
        existing_type=sa.VARCHAR(length=64),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("ix_uploaded_images_user", table_name="uploaded_images")
    op.drop_index("ix_uploaded_images_thread", table_name="uploaded_images")
    op.drop_index("ix_uploaded_images_project", table_name="uploaded_images")
    op.drop_index("ix_uploaded_images_mime", table_name="uploaded_images")
    op.drop_index("ix_uploaded_images_created", table_name="uploaded_images")
    op.drop_table("uploaded_images")
    op.drop_index(
        "ix_uploaded_documents_thread", table_name="uploaded_documents"
    )
    op.drop_index(
        "ix_uploaded_documents_project", table_name="uploaded_documents"
    )
    op.drop_index("ix_uploaded_documents_mime", table_name="uploaded_documents")
    op.drop_index(
        "ix_uploaded_documents_created", table_name="uploaded_documents"
    )
    op.drop_table("uploaded_documents")
    op.drop_index("ix_tts_outputs_thread", table_name="tts_outputs")
    op.drop_index("ix_tts_outputs_provider", table_name="tts_outputs")
    op.drop_index("ix_tts_outputs_project", table_name="tts_outputs")
    op.drop_index("ix_tts_outputs_created", table_name="tts_outputs")
    op.drop_table("tts_outputs")
    op.drop_index("ix_generated_images_user", table_name="generated_images")
    op.drop_index("ix_generated_images_thread", table_name="generated_images")
    op.drop_index("ix_generated_images_project", table_name="generated_images")
    op.drop_index("ix_generated_images_created", table_name="generated_images")
    op.drop_table("generated_images")
    op.drop_index(
        "ix_generated_documents_thread", table_name="generated_documents"
    )
    op.drop_index(
        "ix_generated_documents_project", table_name="generated_documents"
    )
    op.drop_index(
        "ix_generated_documents_format", table_name="generated_documents"
    )
    op.drop_index(
        "ix_generated_documents_created", table_name="generated_documents"
    )
    op.drop_table("generated_documents")
    # ### end Alembic commands ###
