"""create all tables from models

Revision ID: ac973209add4
Revises: 2fa2ab3faac6
Create Date: 2025-10-26 21:38:42.493238

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac973209add4"
down_revision: Union[str, Sequence[str], None] = "2fa2ab3faac6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "events_outbox",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.String(length=64),
            server_default="default",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_events_outbox_status_created",
        "events_outbox",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_events_outbox_tenant_id",
        "events_outbox",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "memory_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("silo", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column(
            "pinned", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "silo IN ('ephemeral', 'midterm', 'longterm')",
            name="memory_entries_silo_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memory_entries_silo", "memory_entries", ["silo"], unique=False
    )
    op.create_index(
        "ix_memory_entries_silo_updated",
        "memory_entries",
        ["silo", "updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_memory_entries_user_silo",
        "memory_entries",
        ["user_id", "silo"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("thread_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.String(length=64),
            server_default="default",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_messages_thread_id_timestamp",
        "messages",
        ["thread_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sync_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("connector_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sync_jobs_connector_created",
        "sync_jobs",
        ["connector_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "chat_threads",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["chat_threads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_threads_parent_id", "chat_threads", ["parent_id"], unique=False
    )
    op.create_index(
        "ix_chat_threads_project_id",
        "chat_threads",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_chat_threads_updated",
        "chat_threads",
        [sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_chat_threads_user_id", "chat_threads", ["user_id"], unique=False
    )
    op.create_table(
        "connector_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "document_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["config_id"], ["connector_configs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_connector_runs_config_started",
        "connector_runs",
        ["config_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "raw_documents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=512), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["config_id"], ["connector_configs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_raw_documents_config_external",
        "raw_documents",
        ["config_id", "external_id"],
        unique=True,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["chat_threads.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_messages_thread_created",
        "chat_messages",
        ["thread_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_chat_messages_thread_id",
        "chat_messages",
        ["thread_id"],
        unique=False,
    )
    op.drop_index(op.f("idx_audit_log_entity"), table_name="audit_log")
    op.drop_index(op.f("idx_audit_log_ts"), table_name="audit_log")
    op.create_index(
        "ix_audit_log_entity",
        "audit_log",
        ["entity", "entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_timestamp",
        "audit_log",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_log_timestamp", table_name="audit_log")
    op.drop_index("ix_audit_log_entity", table_name="audit_log")
    op.create_index(
        op.f("idx_audit_log_ts"),
        "audit_log",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_audit_log_entity"),
        "audit_log",
        ["entity", "entity_id"],
        unique=False,
    )
    op.drop_index("ix_chat_messages_thread_id", table_name="chat_messages")
    op.drop_index("ix_chat_messages_thread_created", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(
        "ix_raw_documents_config_external", table_name="raw_documents"
    )
    op.drop_table("raw_documents")
    op.drop_index(
        "ix_connector_runs_config_started", table_name="connector_runs"
    )
    op.drop_table("connector_runs")
    op.drop_index("ix_chat_threads_user_id", table_name="chat_threads")
    op.drop_index("ix_chat_threads_updated", table_name="chat_threads")
    op.drop_index("ix_chat_threads_project_id", table_name="chat_threads")
    op.drop_index("ix_chat_threads_parent_id", table_name="chat_threads")
    op.drop_table("chat_threads")
    op.drop_index("ix_sync_jobs_connector_created", table_name="sync_jobs")
    op.drop_table("sync_jobs")
    op.drop_table("projects")
    op.drop_index("ix_messages_thread_id_timestamp", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_memory_entries_user_silo", table_name="memory_entries")
    op.drop_index("ix_memory_entries_silo_updated", table_name="memory_entries")
    op.drop_index("ix_memory_entries_silo", table_name="memory_entries")
    op.drop_table("memory_entries")
    op.drop_index("ix_events_outbox_tenant_id", table_name="events_outbox")
    op.drop_index("ix_events_outbox_status_created", table_name="events_outbox")
    op.drop_table("events_outbox")
    op.drop_table("connector_configs")
    # ### end Alembic commands ###
