#!/usr/bin/env python3

import re
import subprocess
from pathlib import Path

TEST_LOG = Path("test_logs.txt")
PATCH_PLAN = Path("patchplan.md")


def run_tests():
    print("🧪 Running test suite...")
    subprocess.run(["./run_tests.sh"], shell=True, check=False)


def extract_failures():
    if not TEST_LOG.exists():
        print("❌ No test_logs.txt found.")
        return []

    with open(TEST_LOG) as f:
        lines = f.readlines()

    failures = []
    current_trace = []
    capture = False

    for line in lines:
        if re.match(r"_{5,}.*_{5,}", line):
            if current_trace:
                failures.append("".join(current_trace))
                current_trace = []
            capture = True
        if capture:
            current_trace.append(line)

    if current_trace:
        failures.append("".join(current_trace))

    return failures


def write_patch_plan(failures):
    with open(PATCH_PLAN, "w") as f:
        f.write("# 🔧 Patch Plan (Auto-Generated by KimiBox)\n\n")
        if not failures:
            f.write("✅ All tests passed. No patch required.\n")
            return

        for i, failure in enumerate(failures, 1):
            f.write(f"## Failure {i}\n")
            f.write("```text\n")
            f.write(failure.strip())
            f.write("\n```\n\n")
            f.write("**Probable Cause**: <!-- Add hypothesis here -->\n\n")
            f.write("**Suggested Fix**: <!-- Describe fix or command -->\n\n")
            f.write("---\n")

    print(f"📄 Patch plan written to {PATCH_PLAN}")


if __name__ == "__main__":
    run_tests()
    failures = extract_failures()
    write_patch_plan(failures)
